### ISSUE TITLE
Incorrect result from concurrent updates/deletes -- case 2

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#162]
This is another case returning wrong results on concurrent locking reads/updates/deletes.

```
create table t1 (id1 int, id2 int, value int, primary key (id1, id2)) engine=rocksdb;
insert into t1 values (1, 1, 1),(1, 2, 1),(1, 3, 1), (2, 2, 2);

Client 1:
update t1 set value=100 where id1=1;

Client 2:
delete from t1 where id1=1 and id2=1;

Client 1:
select * from t1 for update;

Client 2 executed delete after Client 1 read the first row and before locked the first row. Expected result was (id1, id2)=(1,1) being deleted, and for (id1, id2)=(1,2) and(1,3) value should be updated to 100. But actually the first update did not update anything, so value remained 1 and 1 respectively.
```

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D53985 is a reproducible test case.

**Comment by spetrunia** [comment]
(I wanted to look at this issue as it might relate to #165 that I'm working on) 

This issue seems to be caused by the "delay snapshots until first operation" feature in 0891be127b8ff360a773cd04b83257f3fec47dc5.

The statement

```
  update t1 set value=100 where id1=1;
```

runs as follows:
- Client#1 reads row (1,1,1) through an Iterator. It is not using any snapshot.
- Client#2 comes, deletes row (1,1,1), and commits
- Client#1 calls GetForUpdate() for row (1,1,1)
  - GetForUpdate() is called.
  - Snapshot is created. It is based on the current sequence number (i.e the number after the action of Client#2)
  - We try to get the record (1,1,1) using the snapshot, and it to be gone (**)
- HA_ERR_END_OF_FILE is returned to the SQL layer, which assumes there are no more records with id1=1, and stops the scan.

The code that was written before the "delayed snapshot creation" feature didn't need to care about somebody removing rows it is scanning. RocksDB's TransactionAPI would detect the conflicting row modification at step (**) and return a kBusy error.

The first way to fix this is to make "delay snapshot creation" much less aggressive.  This might remove the benefits we got from delayed snapshot creation, though.

Another way is to make ha_rocksdb.cc code aware that it is not seeing a consistent view of the database (rows might be deleted/modified as we scan them).  I'm not sure how exactly to do this.

**Comment by jkedgar** [comment]
Sergei, I have a diff (https://reviews.facebook.net/D54129) out right now to create a snapshot for the iterator and then just keep using it.  We've run into too many concurrency issues where the iterator is not using the same snapshot as the call to GetForUpdate().  I think that will solve this issue for you.

**Comment by jkedgar** [comment]
On top of this I'm planning on adding code so that if we get a kBusy accessing the first row after the snapshot is created it will release the snapshot and try again.  This is to gain back some of the benefits of delayed snapshot creation.

**Comment by spetrunia** [comment]
I see..  I'm wondering about this patch: https://reviews.facebook.net/D53205  Will it be needed anymore  after D54129 is pushed?

**Comment by jkedgar** [comment]
No it will not be needed anymore once I have the retry option I mentioned.  I'll mark that change as needing to be squashed.

**Comment by yoshinorim** [comment]
https://reviews.facebook.net/D54129 fixed this partially (returning deadlock error instead of silently succeeding)
