### ISSUE TITLE
Data_length in SHOW TABLE STATUS for RocksDB table is reset to zero by ANALYZE TABLE

### ISSUE THREAD

**Issue by valeriikravchuk** [facebook/mysql-5.6#164]
Consider a very small and simple RocksDB table that was created from MyISAM one:

mysql> alter table tr2 engine=RocksDB;
Query OK, 6 rows affected (0.13 sec)
Records: 6  Duplicates: 0  Warnings: 0

mysql> show create table tr2\G
**************************\* 1. row ***************************
       Table: tr2
Create Table: CREATE TABLE `tr2` (
  `id` varchar(10) COLLATE latin1_bin NOT NULL,
  `c1` varchar(10) COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=ROCKSDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin
1 row in set (0.00 sec)

Initially statistcis is far from correct, check number of rows:

mysql> show table status like 'tr2'\G
**************************\* 1. row ***************************
           Name: tr2
         Engine: ROCKSDB
        Version: 10
     Row_format: Dynamic
           Rows: 1
 Avg_row_length: 156
    Data_length: 156
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: NULL
    Update_time: NULL
     Check_time: NULL
      Collation: latin1_bin
       Checksum: NULL
 Create_options:
        Comment:
1 row in set (0.00 sec)

mysql> select \* from tr2;
+----+------+
| id | c1   |
+----+------+
| A  | a    |
| B  | b    |
| c  | X    |
| d  | X    |
| e  | X    |
| f  | e    |
+----+------+
6 rows in set (0.00 sec)

So, we have 6 rows, not one. After the fix for issue #160 ANALYZE should update statistics, and it does:

mysql> analyze table tr2;
+----------+---------+----------+----------+
| Table    | Op      | Msg_type | Msg_text |
+----------+---------+----------+----------+
| test.tr2 | analyze | status   | OK       |
+----------+---------+----------+----------+
1 row in set (0.11 sec)

mysql> show table status like 'tr2'\G
**************************\* 1. row ***************************
           Name: tr2
         Engine: ROCKSDB
        Version: 10
     Row_format: Dynamic
           Rows: 6
 Avg_row_length: 0
    Data_length: 0
Max_data_length: 0
   Index_length: 0
      Data_free: 0
 Auto_increment: NULL
    Create_time: NULL
    Update_time: NULL
     Check_time: NULL
      Collation: latin1_bin
       Checksum: NULL
 Create_options:
        Comment:
1 row in set (0.00 sec)

We see 6 rows, as expected, but now check Data_length, it's reset to 0 (zero), and this is hardly correct (for optimizer at least).

**Comment by alxyang** [comment]
after some investigation, found this comment inside `rocksdb.show_table_status` test

"Some statistics don't get updated as quickly.  The Data_length and
Avg_row_length are trailing statistics, meaning they don't get updated
for the current SST until the next SST is written."

so this is a known 'feature' and expected behaviour.
since there arent enough rows, the statistics for data_length/avg_row_length for this current SST are not yet updated. They wont be visible until the next SST is created.

if we want to handle cases where there are only few rows in the table, changes in the RocksDB side need to be made. Am not sure why it is implemented this way. Currently investigating this further.
