### ISSUE TITLE
ALTER TABLE ADD UNIQUE INDEX doesn't work

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#178]
Daniel found the bug. How to repeat:

```
mysql> create table t1 (c1 int, c2 int, c3 char(10), c4 char(20));
Query OK, 0 rows affected (0.51 sec)
mysql> ALTER TABLE t1 ADD UNIQUE KEY uidx ( c4(10), c3 );
ERROR 1030 (HY000): Got error 122 from storage engine
```

**Comment by alxyang** [comment]
@yoshinorim this is expected behavior.  Notice the table does not have a primary key.  Remember we decided to temporarily disable unique indexes for tables with no pk for now.  There is a check in `ha_rocksdb::create` that disables this

if we still want this feature i can assign it to myself since i am familiar with the code for this area

**Comment by yoshinorim** [comment]
Yeah let's return better error message:)
