### ISSUE TITLE
Number of rows affected differs between RocksDB and InnoDB for an empty table

### ISSUE THREAD

**Issue by RoelVdP** [facebook/mysql-5.6#204]
```
DROP DATABASE test;CREATE DATABASE test;USE test;
CREATE TABLE t1 AS SELECT UUID(), LENGTH(UUID());
ALTER TABLE t1 ADD c2 FLOAT NOT NULL;

With: --no-defaults --default-storage-engine=InnoDB

Gives:
mysql> ALTER TABLE t1 ADD c2 FLOAT NOT NULL;
Query OK, 0 rows affected (0.14 sec)
Records: 0  Duplicates: 0  Warnings: 0

With: --no-defaults --default-tmp-storage-engine=MyISAM --rocksdb --skip-innodb --default-storage-engine=RocksDB

Gives:
mysql> ALTER TABLE t1 ADD c2 FLOAT NOT NULL;
Query OK, 1 row affected (0.06 sec)
Records: 1  Duplicates: 0  Warnings: 0

Note that in second example there is one row affected.
```

**Comment by tplavcic** [comment]
It differs from InnoDB also on tables that have data in it, but that might be intentional.
InnoDB seems to report 0 affected rows for alter table while RocksDB seems to report the number of rows in the table (but even if true the initial report stands).

RocksDB

```
mysql> create table test2(a int not null);
Query OK, 0 rows affected (0.12 sec)

mysql> insert into test2 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into test2 values (2);
Query OK, 1 row affected (0.00 sec)

mysql> alter table test2 add column b int;
Query OK, 2 rows affected (0.17 sec)
Records: 2  Duplicates: 0  Warnings: 0
```

InnoDB

```
mysql> create table test2(a int not null);
Query OK, 0 rows affected (0.21 sec)

mysql> insert into test2 values (1);
Query OK, 1 row affected (0.03 sec)

mysql> insert into test2 values (2);
Query OK, 1 row affected (0.03 sec)

mysql> alter table test2 add column b int;
Query OK, 0 rows affected (0.35 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

**Comment by yoshinorim** [comment]
Does this block your tests? I'm not sure if it needs to be fixed..

**Comment by RoelVdP** [comment]
Hi @yoshinorim 

It does not. However, we're seeing quite a few issues so any differences seen will be compounding work and filtering over time.

**Comment by jkedgar** [comment]
The reason for the difference is that InnoDB is able to do an in-place alter so no rows are copied.  RocksDB, due to its different format, can't do an in-place alter so a new table is created and the rows are copied from the old to the new.  If you do an alter where RocksDB _can_ do the work in-place, the result matches InnoDB's output.

```
mysql> create table test2 (a int not null, b int);
Query OK, 0 rows affected (0.00 sec)

mysql> insert into test2 values (1, 1);
Query OK, 1 row affected (0.00 sec)

mysql> insert into test2 values (2, 2);
Query OK, 1 row affected (0.00 sec)

mysql> alter table test2 add key(b);
Query OK, 0 rows affected (0.07 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

You can see the code that is generating this at https://github.com/facebook/mysql-5.6/blob/fb-mysql-5.6.35/sql/sql_table.cc#L9091.  The variable 'copied' is only set to a non-zero value at this line which is only referenced if we can't do an in-place alter.

I'm going to close this issue since this isn't a bug.
