### ISSUE TITLE
There's no more COMPRESSION syntax from 5.6.24 branch. But no commit history for these

### ISSUE THREAD

**Issue by SunguckLee** [facebook/mysql-5.6#217]
We are using facebook compression features with LZ4 algorithm.
We are going to upgrade facebook mysql 5.6.27, but this version doesn't have lz4_embedded source tree any more.

But looks like there's no commit history for these changes (Why lz4 algorithm removed).

We can't use LZ4 algorithm with facebook mysql anymore ?
Thanks.

**Comment by jtolmer** [comment]
We never completed the development and testing of the pluggable compression support to the point that we were comfortable deploying it to production. Instead, the team switched focus to the MyRocks project. Since the compression support was never deemed production-ready, and keeping the code in the source tree was a maintenance burden, I removed the all the commits from our source history when I rebased our commits on top of 5.6.27.
