### ISSUE TITLE
Sort order for varchars is different between MyISAM/InnoDB vs MyRocks

### ISSUE THREAD

**Issue by lth** [facebook/mysql-5.6#257]
In MyRocks, there is an assumption that shorter strings sort before longer strings. This is actually not true in InnoDB or in MyISAM. If a string is shorter, it gets padded with spaces in MyISAM (which has sort weight of 0x20).

In InnoDB, we use strnncollsp (as opposed to just strnncoll) which will do the sorting correctly.

This is an issue, because we do filesort using MyISAM, which means that we might get back results in different orders, depending on the query plan.

To repro:

```
create table t (id int not null auto_increment primary key,
                c2 varchar(64) CHARACTER SET latin1 COLLATE latin1_bin,
                key (c2));

insert into t (c2) values (_latin1 0x0), (_latin1 0x9), (_latin1 0x20), (_latin1 0x62), ('');

explain select hex(c2),hex(weight_string(c2)) from t order by c2, hex(c2) asc;
select hex(c2),hex(weight_string(c2)) from t order by c2, hex(c2)  asc;

explain select hex(c2),hex(weight_string(c2)) from t order by c2 asc;
select hex(c2),hex(weight_string(c2)) from t order by c2 asc;

drop table t;
```

The test case results:

```
create table t (id int not null auto_increment primary key,
c2 varchar(64) CHARACTER SET latin1 COLLATE latin1_bin,
key (c2));
insert into t (c2) values (_latin1 0x0), (_latin1 0x9), (_latin1 0x20), (_latin1 0x62), ('');
explain select hex(c2),hex(weight_string(c2)) from t order by c2, hex(c2) asc;
id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  t       index   NULL    c2      67      NULL    1       Using index; Using filesort
select hex(c2),hex(weight_string(c2)) from t order by c2, hex(c2)  asc;
hex(c2) hex(weight_string(c2))
00      00
09      09

20      20
62      62
explain select hex(c2),hex(weight_string(c2)) from t order by c2 asc;
id      select_type     table   type    possible_keys   key     key_len ref     rows    Extra
1       SIMPLE  t       index   NULL    c2      67      NULL    1       Using index
select hex(c2),hex(weight_string(c2)) from t order by c2 asc;
hex(c2) hex(weight_string(c2))

00      00
09      09
20      20
62      62
drop table t;
```

**Comment by lth** [comment]
This is where the assumption is made:
https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/storage/rocksdb/rdb_datadic.cc#L1274-L1286

**Comment by spetrunia** [comment]
Confirm. Affects unique keys, too:

```
create table t2 ( 
  pk varchar(64) CHARACTER SET latin1 COLLATE latin1_bin,
  col1 varchar(64),
  primary key (pk)
);
```

```
insert into t2 values ('a','a');
insert into t2 values ('a ', 'a-space');
```

The second insert fails for InnoDB, works for MyRocks.

**Comment by spetrunia** [comment]
The manual describes the required behavior here: 
http://dev.mysql.com/doc/refman/5.7/en/charset-binary-collations.html

**Comment by hermanlee** [comment]
For uniqueness, we could strip off trailing padspace when creating the key and use unpack_info to rebuild it potentially.

Sort order on varchar seems much harder to make memcomparable. A string like "a              \t" (i.e. a, followed by a number of spaces, followed by the tab character) needs to be sorted before the string "a" because "a" is treated as "a                       ". For varbinary, the trailing padding character is 0x00, so a string like "a" would naturally sort before "a\t".

**Comment by lth** [comment]
I think we can fix this by changing the memcomparable form. The encoding is as follows:
1. Strip all trailing spaces.
2. Extend unpack_info to indicate how many trailing spaces are supposed to be present.
3. Currently, in the memcomparable form, the 0x0 character is currently used for padding. use 0x20 (space) instead.
4. In the memcomparable form, for every 9th character, we do _not_ write out 255 - pad. Instead we write out the following depending on the suffix. Write 0 if the suffix sorts less than all spaces. Write 1 if the suffix sorts equal to all spaces. Write 2 if suffix sorts as greater than all spaces.

As an example, consider the following varchars (I use underscore to denote space). Also, instead of every 9th byte, I use every 5th byte for simplicity.

```
_ _ _ _ _ _ _ _ a    -> _ _ _ _ 2 _ _ _ _ 2 a _ _ _ 1
_                    -> _ _ _ _ 1
_ _ _ _ _ _ _ _ _    -> _ _ _ _ 1
_ _ _ _ _ _ _ _ 0x1  -> _ _ _ _ 0 _ _ _ _ 0 0x1 _ _ _ 1
```

Just to walk through an example, for the first value in the first row, the suffix is "_ _ _ _ a". This sorts greater than all spaces, so we write a 2. For the second value, the suffix is "a". This sorts greater, so write 2 again.

For the second and third example, the suffix compares as equal to all spaces. Note that because we strip out trailing spaces in step 1, during key creation, we use the empty string as the sort key.

For the 4th example, the suffix "_ _ _ _ 0x1" compares less than all spaces, so we write a 0. For the next value "0x1" compares less than all spaces, so we write 0 again.

**Comment by spetrunia** [comment]
Agree with the suggested encoding.
- Can't avoid using unpack_info, because 'a' and 'a ' must have identical mem-comparable forms, but we still need to restore the initial value.
- decode_info as suggested is sufficient: when decoding, we can look at 9th byte. 0 or 2 means continue encoding, 1 means the this is the last 9-byte chunk.

On the SQL side
- CHARSET_INFO has pad_char member.  (However for multi-byte charsets/collations like ucs2 the space is encoded as two bytes, 0x0020. It seems, padding in mem-comparable form should use strxfrm(pad_char)?)
- Also need to figure out whether this should be used to use for prefix indexes ( INDEX(column(n))

**Comment by lth** [comment]
I just realized that your change requires adding unpack info to PKs (for PKs containing varchars).

I've actually written support for that here (not checked in though): https://reviews.facebook.net/D58503

**Comment by lth** [comment]
While I was investigating #261, I found another twist to this sort order problem.

The "binary" collation behaves like our previous behaviour (note, this is different from latin1_bin). There is no padding at the end, and shorter strings sort before longer strings.

If you look at Field_varstring::make_sort_key, you'll note a special case for the binary collation. We store the length in the sort key, because 'a' and 'a ' (with space) needs to have different sort keys even though strnxfrm will output the same key.

**Comment by spetrunia** [comment]
More details about collations, part#1: levels

A collation has "level" characteristic. Most of MySQL collations have level=1. 
With level=1, mem-comparable form of a string is a concatenation of mem-comparable forms of its characters. That is, the following holds:

```
  strxfrm(concat(str1, str2)) = concat(strxfrm(str1), strxfrm(str2))
```

This equivalence is actually essential for patch D59553 to work. We are mostly ok, the equivalence holds for most of MySQL's charsets. There are two exceptions  (btw MariaDB has more than two):

```
latin2_czech_cs: levels_for_compare=4 levels_for_order=4
cp1250_czech_cs: levels_for_compare=2 levels_for_order=2
```

These collations do have PAD characteristic, so they require endspace padding. A demo of the effect of padding space for collation with levels=2:

```
suppose strxfrm('ab')= 'pqrst'.  
```

Then 

```
strxfrm('ab ') = pqWWrstZZ
```

that is, adding a space at the end produces extra bytes in the middle!

A proposed solution for cp1250_czech_cs and latin2_czech_cs: do padding the 'dumb' way and do not try to save spaces at the end. It's not efficient but we don't have to be for these collations. 

I think, fixing these collations can be done outside of D59553.

**Comment by spetrunia** [comment]
More details about collations, part#2: on the size of mem-comparable images.

D59553 has an issue when mem-comparable image of the last padding space character stretches across the last segment used by the value.

One of possible solutions is to pick the segment size (aka RDB_ESCAPE_LENGTH-1) to be such that mem-comparable image of the padding character (space) does not ever stretch across segment bound.

Is this possible?

Here is a list of all collations, with their `length(strxfrm(' '))`: 
https://gist.github.com/spetrunia/08c6d26300cd4350f34fee3a5e4b6234

Here is a short list, with collations that have `length(...)` > 1:
https://gist.github.com/spetrunia/8520837ba06079549fe005abe2a81912
- latin2_czech_cs and cp1250_czech_cs were discussed in the previous comment.
- In utf8mb4_bin, utf16_bin, utf16le_bin, utf32_bin, all characters produce 
  one weight element, which is 3 bytes long (That is, if (RDB_ESCAPE_LENGTH-1) is 
  divisible by 3, then character's mem-comparable image will not be split across
  segments).
- In utf8_bin, ucs2_bin - one character produces 1 weight, 1 weight = 2 bytes.
- In ucs2_general_mysql500_ci, utf8_general_mysql500_ci, one character produces 
  one weight, each weight is 2 bytes long.
- In utf8mb4_general_ci, utf32_general_ci, utf16_general_ci - same as above. 1
  char has 1 weight, 1 weight = 2 bytes  (all non-BMP characters have the same weight of 0xFFFD)
- utf8_unicode_ci, utf32_unicode_ci, utf8mb4_unicode_ci, ucs2_unicode_ci, and all 
  collations matching the pattern {utf8,utf32,utf8mb4,ucs2}_{$nation}_ci are using 
  UCA (Unicode Collation Algorithm).
  In UCA, a symbol produces 0..8 weights, each weight is 2 bytes. (That is, if 
  segment size is even, we're ok).

Conclusion: mem-comparable image of the space will not be split if (RDB_ESCAPE_LENGTH-1) is divisible
- by 2, for most charsets,
- by 3, for a few charsets.

**Comment by spetrunia** [comment]
So, there are two approaches to continue with D59553

S1.  Change RDB_ESCAPE_LENGTH so that mem-comparable image of space is never split between segments.

Advantages of this approach:
- We won't need to store #bytes_used_for_padding and #trimmed_spaces in unpack_info.
  There will be only one number, it will be `(#trimmed_spaces - #spaces_added_for_padding)`
- More dense packing? Packing 3-byte entities into 8-byte segments (where 100% efficiency can only be achieved when `24*n` etc bytes are used) seems to be not as efficient as packing into 9-byte segments where we achieve 100% efficiency every time `9*n` bytes are used).

S2. Make constant RDB_ESCAPE_LENGTH work with all charsets. 

The used approach to cut off the endspaces is based on cutting off the tail that consists of one-byte space characters:

   0x20 0x20 0x20 ...

In order to maintain sorting, we use three values for suffixes that compare as
- less than "0x20 0x20 ..."
- equal to "0x20 0x20 ..."  (in this case, the suffix is removed)
- greater than "0x20 0x20 ..."

Now, suppose the image of space is 3 bytes, 0xAB 0xCD 0xEF. Depending on where the string is cut off, the end-space suffix may look like:

  0xAB 0xCD 0xEF,0xAB ...
  0xCD 0xEF,0xAB 0xCD ...
  0xEF,0xAB 0xCD 0xAB ...

In order to remove these suffixes and maintain sorting, we will need to use multiple constants as segment separators.  
The constants will indicate that the suffix compares as:
- less than "0xAB 0xCD 0xEF,0xAB ..."
- equal to "0xAB 0xCD 0xEF,0xAB ..." (in this case, the suffix is removed)
- between the above and "0xCD 0xEF,0xAB 0xCD ..."
- equal to "0xCD 0xEF,0xAB 0xCD ..." (in this case, the suffix is removed)
- between the above and "0xEF,0xAB 0xCD 0xAB ..."
- equal to "0xEF,0xAB 0xCD 0xAB ..." (in this case, the suffix is removed) 
- greater than "0xEF,0xAB 0xCD 0xAB ..."  

S1 seems to be a lot simpler. I'll implement S1.

**Comment by spetrunia** [comment]
S1 implemented, see D59553.

**Comment by spetrunia** [comment]
On saving the original number of end-spaces in unpack_info.

The current patch uses two numbers
- n_trimmed (1 or 2 bytes)
- n_padded (1 byte)

As noted by @lth, this is excessive.

With recent fixes, we can be certain that the last segment ends on a character bound.
So, for a VARCHAR(N) column
- Up to N spaces can be trimmed from the value
- then, up to MAX(9/3, 8/2, 8/1) = 8 mem-comparable images of space can be added as padding.

That is, we could use a single `n_trimmed` value with range `[-8, n]`, where
- negative values mean spaces were added as padding
- positive values mean spaces were removed

We could store `n_trimmed + 8` to not lose one bit for the sign.
