### ISSUE TITLE
Issuing a manual compaction to MyRocks hangs new connections

### ISSUE THREAD

**Issue by hermanlee** [facebook/mysql-5.6#286]
Trying to compact a column family manually. But during the compaction, new connections to the mysqld server times out on the default settings.

**Comment by yoshinorim** [comment]
I could reproduce the issue. Here is a stack trace -- https://phabricator.intern.facebook.com/P56527352

The problem is, SET statement actually holds a global mutex LOCK_global_system_variables during the statement (see sys_var::update()). The mutex was needed to initialize THD too. So if SET statement takes long time, all new incoming connections are blocked:(

We have to deprecate rocksdb_force_flush_memtable_now. I think the right way is implementing as UDF or a new native SQL function.

**Comment by yoshinorim** [comment]
The easiest fix is moving rocksdb_force_flush_memtable_now() from update() to check() function. check() doesn't hold the global mutex so it doesn't block other connections.

**Comment by gunnarku** [comment]
Workaround implemented.
