### ISSUE TITLE
explain hermitage failures

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#310]
Assigned to Yoshinori who added the hermitage tests

See https://github.com/vadimtk/hermitage/blob/master/mysql-rocksdb.md
and
https://twitter.com/VadimTk/status/771564816250974208

We have hermitage tests...
https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/mysql-test/suite/rocksdb/t/hermitage.test

**Comment by mdcallag** [comment]
Also...

In the related note, MyRocks in more cases (you can find on the same page),
often shows "ERROR 1205 (HY000): Lock wait timeout exceeded;", but it
happens almost immediately, without any visible wait.

**Comment by vadimtk** [comment]
I do not know if "ERROR 1205 (HY000): Lock wait timeout exceeded;" is intended behavior or a bug. If this is intended,  probably more clear error would be better, even "DEADLOCK" would work.

**Comment by yoshinorim** [comment]
@vadimtk In your Lost Update test, I assume you really hit lock wait timeout in MyRocks. This was because default rocksdb_lock_wait_timeout is only 1 second (mainly because currently MyRocks does not support auto deadlock detection), and you didn't execute commit(T1) immediately. If you increase rocksdb_lock_wait_timeout large enough, you'll see a different error message for T2 on update -- "ERROR 1213 (40001): Deadlock found when trying to get lock; try restarting transaction".

Here is our test case to cover the scenario.
https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/mysql-test/suite/rocksdb/t/hermitage.inc#L136

**Comment by yoshinorim** [comment]
About Read Skew (G-single), yes, MyRocks prevents Read Skew with Repeatable Read, so it's different from InnoDB, and it's more like PostgreSQL.

**Comment by vadimtk** [comment]
@yoshinorim 

Right, I think the main bug is https://github.com/vadimtk/hermitage/blob/master/mysql-rocksdb.md#predicate-many-preceders-pmp
in predicate-many-preceders - read only - there is no repeatable read.

**Comment by yoshinorim** [comment]
@vadimtk I can't reproduce your "MyRocks "repeatable read" DOES NOT prevent Predicate-Many-Preceders (PMP) for read predicates:" case. RR didn't return (3, 30) and there is a test case -- https://github.com/facebook/mysql-5.6/blob/webscalesql-5.6.27.75/mysql-test/suite/rocksdb/t/hermitage.inc#L96 . Could you please try again and run mtr --suite=rocksdb hermitage and see if it passes?

**Comment by vadimtk** [comment]
@yoshinorim I can't repeat anymore. Yesterday I repeated 2 times.
Probably we can close for now.
