### ISSUE TITLE
Change snapshot conflict error handling on Read Committed

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#340]
MyRocks RC behavior is currently different from InnoDB and PostgreSQL. In short, MyRocks may return more errors (http://www.slideshare.net/matsunobu/myrocks-deep-dive/88). There are cases where we should not return many errors.

Current implementation is:
T1: lock row 1
 create snapshot
 read row 1
 lock row 2
 read row 2

and if T2 updates row 2 before T1 locks, T1 gets "deadlock" error. What I'd like to change is, with RC isolation, when getting deadlock error, creating another snapshot then continue. This is closer to InnoDB behavior.

**Comment by jkedgar** [comment]
@yoshinorim , can you provide more clarification?  T1 would only get a deadlock if it attempted to lock the row for update.  Normal access (read only) to the row would be covered by the existing snapshot.  Attempting to lock the row for update would not be solved by applying a new snapshot.  Am I missing something?

**Comment by jkedgar** [comment]
https://reviews.facebook.net/D65469

**Comment by mdcallag** [comment]
I don't understand. Then I went back and reviewed what PG explains for RC and I kind of get it.

But first, why does it get a deadlock error, because that is a lock wait not a deadlock?

From my notes -- https://github.com/mdcallag/mytools/wiki/Cursor-Isolation -- I followed link to PG RC docs and what PG claims is: T1 will block waiting for T2 to unlock/commit/rollback. If T2 doesn't commit a change, then T1 continues with its snapshot. If T2 does commit a change it will use the committed version of the row and the manual includes this warning:
"Because of the above rule, it is possible for an updating command to see an inconsistent snapshot: it can see the effects of concurrent updating commands on the same rows it is trying to update, but it does not see effects of those commands on other rows in the database."
See https://www.postgresql.org/docs/9.4/static/transaction-iso.html

**Comment by jkedgar** [comment]
It is a deadlock because there is no way we can ever get the lock.  T2 has modified the row, changing the sequence number, and the lock is tied to the sequence number so we would wait forever if we didn't timeout.  To successfully get the lock on that row we need a snapshot that has the current row's sequence number (or larger).  Thus we are releasing the old snapshot and acquiring a new one.

**Comment by hedengcheng** [comment]
@yoshinorim 
In my knowledge of MySQL(InnoDB)'s transaction and mvcc implementation. I classify the read into two categories: 
1. snapshot read. Which read a dedicated snapshot. For RC, the snapshot(ReadView) is created at every statement. For RR, the snapshot is created at transaction start.
2. current read. Which read the newest version of the record, without snapshot. In InnoDB, current read don't create any snapshot at all. 

SQL without lock use snapshot read, SQL with lock use current read, just lick select ... lock in share mode(for update), update, delete, and so on.

So I think its an isolation standard, the two implementations are all OK. But consider the compatibility with InnoDB, i prefer this change.

**Comment by yoshinorim** [comment]
@hedengcheng In this task, I'm talking about single statement, multiple (potentially very large) row lock statement. http://www.slideshare.net/matsunobu/myrocks-deep-dive/88 is an example. Previously, MyRocks RC created a snapshot when locking the first row, then used the snapshot for the entire statement. If other clients modify and commited rows that the long running statement had not touched yet, the long running statement got kBusy() error from GetForUpdate(), which was translated into deadlock in MyRocks. Jay's diff (https://reviews.facebook.net/D65469) changed the behavior -- when getting kBusy(), re-creating snapshot then continue. This matches InnoDB RC behavior.

**Comment by hedengcheng** [comment]
@yoshinorim I read the code of the range update. First it read the record with snapshot's sequence number, then call GetForUpdate() to lock this record and check whether it has a newer version. If it has, then return kBusy(). For every record we read, we should double check it for concurrent update, i think its very inefficient. 

But for transactional statement like select ... for update or delete/update, instead of get the current sequence number for the snapshot, we can give a virtual MAX sequence number to it, then we can simulate the current read in InnoDB. Because the statement's snapshot is a max sequence number, so we can see every record's newest version, lock it, eliminate the double check. Is this OK?

**Comment by yoshinorim** [comment]
Need to address Manuel's comment --- https://reviews.facebook.net/D65469

**Comment by siying** [comment]
@hedengcheng RocksDB (or LevelDB) is not designed with the support of snapshot ID to be larger than the current one. We don't fully understand the behavior will be.

For example, very likely, Seek(seek_key) + Prev() can end up with a key which is larger than seek_key. Even if in RocksDB we try to fix those issues, MyRocks will need to change code to handle some weird behavior too. For example, if you want to do a reverse range query from a stop key `stop_key`, currently,  you may do this:

```
iter->Seek(stop_key);
if (!iter->Valid()) {
   iter->SeekToLast();
} else {
   iter->Prev();
}
...
```

This is very straight-forward. However, if you assume new keys can be inserted at any time and they are visible. You need to do something like this:

```
iter->Seek(stop_key);
if (!iter->Valid()) {
   iter->SeekToLast();
} else {
   iter->Prev();
}

while (iter->Valid() && iter->key() >= stop_key) {
   iter->Prev();
}
...
```

This is much trickier.

You also need to handle the case where in same iterating, you see partial updates from one commit. If another transaction updates 4 keys. You may see 2 out of 4.

RocksDB's snapshot creating is not very heavy. So the performance of the current implementation may not be too bad. In case there is a performance problem, I suggest we explore some more easier solution first.

**Comment by yoshinorim** [comment]
https://github.com/facebook/mysql-5.6/pull/362

**Comment by yoshinorim** [comment]
https://github.com/facebook/mysql-5.6/pull/378
