### ISSUE TITLE
Crash-safe auto_increment values

### ISSUE THREAD

**Issue by electrum** [facebook/mysql-5.6#468]
InnoDB had a long-standing bug, finally fixed in 8.0, that auto_increment values were lost on server restart: http://bugs.mysql.com/bug.php?id=199

According to a comment on #39, it seems that MyRocks might also have the same bug, which would be a regression compared to InnoDB on 8.0.

**Comment by mdcallag** [comment]
FB MySQL is based on 5.6 today. We get grief (some deserved) for not matching InnoDB semantics and I am not sure whether you are asking for MyRocks in FB MySQL 5.6 to match InnoDB in MySQL 5.6 or 8.X.

**Comment by yoshinorim** [comment]
Here is a reference -- http://dev.mysql.com/doc/refman/8.0/en/innodb-auto-increment-handling.html -- "On a server restart during crash recovery, InnoDB initializes the in-memory auto-increment counter using the current maximum auto-increment value stored in the data dictionary system table and scans the redo log for auto-increment counter values written since the last checkpoint. If a redo-logged value is greater than the in-memory counter value, the redo-logged value is applied. However, in the case of a server crash, reuse of a previously allocated auto-increment value cannot be guaranteed. Each time the current maximum auto-increment value is changed due to an INSERT or UPDATE operation, the new value is written to the redo log, but if the crash occurs before the redo log is flushed to disk, the previously allocated value could be reused when the auto-increment counter is initialized after the server is restarted. "

We can do the same thing in MyRocks. Perf penalty with extra redo logging is a potential concern. I think it would make sense to allow both, depending on config variables or table syntax (comments).

**Comment by electrum** [comment]
@mdcallag Thanks for the clarification. I wasn't thinking about 5.6 vs 8.0, just whether or not MyRocks would eventually fix this (or if it's not considered a problem). The behavior is rather unexpected, and users do hit this from time to time (and often find out because it breaks replication).

**Comment by armishra** [comment]
I'm currently working on a solution to this. My current approach is to:
* add a data dictionary type that stores the auto increment value for every table
* I call the Merge Operator when new ids are inserted and override the merge operator to maximize values that are stored.
* the data dictionary value gets written to along the commit path of each transaction
* the value is read back into memory before every call to update_auto_incr_val()
* this will be crash safe since the max value is stored after every committed transaction
