### ISSUE TITLE
Add more support for user and table stats with MyRocks

### ISSUE THREAD

**Issue by mdcallag** [facebook/mysql-5.6#616]
Does MyRocks update the counters for the `DISK_*` columns in `information_schema.user_statistics`?

Same question for `IO_*` columns in `IS.table_statistics`.

**Comment by hermanlee** [comment]
Only some of the read statistics are captured, but they require setting `rocksdb_perf_context_level = 2` for the  `IO_READ_BYTES` and `IO_READ_REQUESTS` counters, and `rocksdb_perf_context_level = 3` for the `IO_READ_SVC_USECS`, `IO_READ_SVC_USECS_MAX`.

```
rocksdb::PerfContext::block_read_byte maps to IO_READ_BYTES
rocksdb::PerfContext::block_read_count maps to IO_READ_REQUESTS
rocksdb::PerfContext::block_read_time maps to IO_READ_SVC_USECS
```

The `rocksdb::perfcontext` values are exported through `IS.rocksdb_perf_context` on a per table basis, but requires setting `rocksdb_perf_context_level` to be higher to get captured. Due to how the stats are captured and for performance reasons, each query's stats are captured an attributed to the first table used in the query, so a query that access multiple tables attribute all of the read requests to the first table. It currently doesn't distinguish between primary vs. secondary key read stats, but adding that might not be difficult if `IO_PRIMARY` and `IO_SECONDARY` should also be filled in.

MyRocks does not separate memtable flush/compaction I/O write bytes on a per table/user basis though.
