### ISSUE TITLE
Deprecate rocksdb_compact_cf

### ISSUE THREAD

**Issue by yoshinorim** [facebook/mysql-5.6#629]
We're going to rename rocksdb_compact_cf to rocksdb_debug_compact_cf, to clarify it is for debugging purpose and not for production, since it's dangerous. For example, invoking multiple manual compactions to the same column family can block all background compactions, which block all writes to different column families.

**Comment by gunnarku** [comment]
Personally I don't think any action is required here. The fact that compaction had side-effects is equivalent to triggering garbage collection, casting pointers in C etc. The fact that functionality is there and can cause problems with improper use doesn't mean that we have to hide or remove it.

Renaming it to `rocksdb_debug_compact_cf` is not semantically correct because it's not debugging related functionality per se, there are legitimate use cases during which we may want to trigger manual compaction.

**Comment by lth** [comment]
Made safe with https://github.com/facebook/mysql-5.6/commit/566b7f095eb1d62a6379c33c911f36d7434898e7
